<a href="https://colab.research.google.com/github/faheemkhaskheli9/Python-Interview/blob/main/coding_interview_remove_island.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def is_border(matrix, x, y):
    if x == 0 or y == 0 or x == (matrix.shape[0]-1) or y == (matrix.shape[1]-1):
        return True
    return False

def in_matrix(matrix, x, y):
    if x >= matrix.shape[0] or y >= matrix.shape[1]:
        return True
    if x < 0 or y < 0:
        return True
    return False

def is_connected(matrix, x, y, new_matrix):
    for new_x, new_y in [[x-1, y],
                         [x+1, y],
                         [x, y-1],
                         [x, y+1]]:

      if in_matrix(matrix, new_x, new_y):
        continue

      if matrix[new_x, new_y] == 1:
        if new_matrix[new_x, new_y] == 0:
          new_matrix[new_x, new_y] = 1
          is_connected(matrix, new_x, new_y, new_matrix)

def remove_island(matrix):
    new_matrix = np.zeros(matrix.shape, dtype="uint8")

    for x in range(matrix.shape[0]):
      for y in range(matrix.shape[1]):
        if matrix[x, y] == 1 and is_border(matrix, x, y):
            new_matrix[x, y] = 1
            is_connected(matrix, x, y, new_matrix)

    print(new_matrix)

In [ ]:
rows = 10
cols = 10
matrix = np.random.randint(0,2, (rows, cols))
new_matrix = np.zeros(matrix.shape, dtype="int8")

print(matrix)
print()

remove_island(matrix)

[[1 1 0 0 1 0 0 1 1 0]
 [0 0 1 0 0 1 1 0 1 1]
 [1 0 0 1 0 0 1 1 0 0]
 [0 0 1 0 0 1 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 1]
 [0 1 1 0 1 1 0 0 1 1]
 [1 1 1 0 1 1 1 0 0 1]
 [0 1 0 0 0 0 0 1 0 0]
 [1 1 0 1 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 0 1 0]]

[[1 1 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 1]
 [0 1 1 0 0 0 0 0 1 1]
 [1 1 1 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0 0]
 [1 1 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 0 1 0]]
